refactor: single wearable schema and multiple wearable types
decentraland/common-schemas pull request #61
Opened 2022-03-21 20:33 UTC by guidota

## Description 

Use single wearable schema for both third party or decentraland wearables. Two types also are provided `StandardWearable ` and `ThirdPartyWearable` containing required properties.

### Validations
Some validations were added to the `MerkleProof` object:
- 'hashingKeys' array can't be empty
- `proof` array can't be empty
- All `hashingKeys` must be present in the wearable metadata object

2022-03-21 20:45 UTC, LautaroPetaccio commented on src/platform/wearables/wearable.ts
> +      }
Content can be typed as a string -> string map:
```suggestion
      content: {
        type: 'object',
        additionalProperties: { type: 'string' },
        required: []
      },
```

2022-03-21 21:12 UTC, guidota commented on src/platform/wearables/wearable.ts
> +        nullable: true
The reason is that 'ajv' complains with errors when optional properties are not marked as `nullable`.

Added some comments to the `validate` function to express these properties are mutually exclusive.

2022-03-24 14:22 UTC, LautaroPetaccio requested changes

2022-03-24 14:22 UTC, LautaroPetaccio commented on src/platform/wearables/wearable.ts
> +  'merkleProof'
Standard wearables don't have the content property as well.

2022-03-24 14:22 UTC, LautaroPetaccio commented on src/platform/wearables/wearable.ts
> +  content?: any
```suggestion
  content?: Record<string, string>
```

2022-03-24 14:42 UTC, LautaroPetaccio approved these changes

2022-03-24 15:17 UTC, merged